### ISSUE TITLE
Revamp explorer landing page [TS, Next, Tailwind]

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA-FRONTEND#36]
Once design mockup is ready, redesign the explorer landing page

**Comment by stephanniegb** [comment]
I would like to work on this

**Comment by Darlington02** [comment]
Link to the Figma file: https://www.figma.com/file/e1Xb0n8gPQ2yKkTco1h7UB/STARKNET-TOKENBOUND?type=design&node-id=0-1&mode=design

@stephanniegb
