### ISSUE TITLE
Display-all-NFT page [TS, Next, Tailwind]

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA-FRONTEND#37]
Once mockup design is ready, redesign this page.

https://starknet-tokenbound.com/wallet/0x538c514b0ecd0cf6446a39646618e495a190a8502416f3af4dd5ce5da8acf22

**Comment by ktarun1419** [comment]
i want to work on this issue @Darlington02

**Comment by ktarun1419** [comment]
Hi @Darlington02 ,
Can you give me the design ?

**Comment by codeWhizperer** [comment]
@ktarun1419 The design will soon be ready

**Comment by ktarun1419** [comment]
Thanks, @codeWhizperer! Please inform me once the design is prepared.

**Comment by codeWhizperer** [comment]
@ktarun1419 The design is ready

Find the link: https://www.figma.com/file/e1Xb0n8gPQ2yKkTco1h7UB/STARKNET-TOKENBOUND?type=design&node-id=0-1&mode=design&t=TMINfrK246xNFOdk-0

**Comment by ktarun1419** [comment]
Thanks, @codeWhizperer! I'll commence my work today.

**Comment by ktarun1419** [comment]
@codeWhizperer, @Darlington02, I've noticed an issue. When the user is not connected, it still displays "loading" with no NFTs to show. Instead, it should display a message prompting the user to connect their wallet. Also, is there any social media group where we can easily connect?

**Comment by codeWhizperer** [comment]
> @codeWhizperer, @Darlington02, I've noticed an issue. When the user is not connected, it still displays "loading" with no NFTs to show. Instead, it should display a message prompting the user to connect their wallet. Also, is there any social media group where we can easily connect?

Yes, you can make a fix, and we'd review the PR

Heres a link to the working group: https://t.me/+uiOWOqUy6HcxOGE0
