### ISSUE TITLE
Redo TBA page. [TS, Next, Tailwind, Starknet.js]

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA-FRONTEND#38]
Once mockup design is ready, redesign the page for each individual tokenbound.

**Comment by Joy-Adah** [comment]
can I do this?

**Comment by Joy-Adah** [comment]
Hi @Darlington02 is the mockup design ready?

**Comment by Darlington02** [comment]
@Joy-Adah no not yet, but would be ready before the week runs out

**Comment by Joy-Adah** [comment]
Hi @Darlington02 any update on the mockup design?

**Comment by codeWhizperer** [comment]
> Hi @Darlington02 any update on the mockup design?

Here's the mock design: 


https://www.figma.com/file/e1Xb0n8gPQ2yKkTco1h7UB/STARKNET-TOKENBOUND?type=design&node-id=0-1&mode=design

**Comment by Joy-Adah** [comment]
thanks @codeWhizperer

**Comment by codeWhizperer** [comment]
@Joy-Adah Any update on this?

**Comment by Joy-Adah** [comment]
@codeWhizperer currently working on it

**Comment by ktarun1419** [comment]
Is this issue closed?

**Comment by Joy-Adah** [comment]
@ktarun1419 I'm assigned to it
