### ISSUE TITLE
implement pop up modal for transferring/sending assets (NFTs/ERC20s)

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA-FRONTEND#44]
Refer to the figma design

**Comment by kenkomu** [comment]
Can I take this?

**Comment by codeWhizperer** [comment]
> Can I take this?

@kenkomu  Welcome to the Token bound project.

Kindly find the Figma link here:  https://www.figma.com/file/e1Xb0n8gPQ2yKkTco1h7UB/STARKNET-TOKENBOUND?type=design&node-id=0-1&mode=design&t=TMINfrK246xNFOdk-0

**Comment by ktarun1419** [comment]
@kenkomu  Are you still working on it?

**Comment by kenkomu** [comment]
> @kenkomu  Are you still working on it?

Yes, I am still working on it.

**Comment by kenkomu** [comment]
I have seen the User Profile Modal and send asset modal. Which specific will I work on?

**Comment by Darlington02** [comment]
Asset modal. You’d need to also make it functional. Use the functions in the SDK to ensure users can transfer out both ERC20s and NFTs.

You could consult the SDK and ask questions on the TG chat :)

**Comment by kenkomu** [comment]
Do you mean the TokenboundClient SDK Methods?

**Comment by kenkomu** [comment]
Hello I am almost done with the design let me send you a screenshot.
![Screenshot from 2024-02-27 10-40-53](https://github.com/Starknet-Africa-Edu/TBA-FRONTEND/assets/95502725/8930ea5c-760e-4b56-ba11-51e2ebfc4650)

**Comment by kenkomu** [comment]
It is also responsive in the mobile devices.

![Screenshot from 2024-02-27 10-43-09](https://github.com/Starknet-Africa-Edu/TBA-FRONTEND/assets/95502725/d4114a9f-0100-4389-89cb-d23afd2be72e)

**Comment by Darlington02** [comment]
Amazing work @kenkomu!

**Comment by kenkomu** [comment]
Thank you. I need a few clarifications.

**Comment by kenkomu** [comment]
Should I add a folder called pop_up at the components folder?

I have also implemented my NFT collection page because I thought the pop_up modal will need it.

**Comment by Darlington02** [comment]
@codeWhizperer

**Comment by kenkomu** [comment]
@codeWhizperer

**Comment by codeWhizperer** [comment]
> @codeWhizperer

yes please, go ahead. sorry for the late  response.

**Comment by kenkomu** [comment]
Should I add a folder called pop_up at the components folder?

I have also implemented my NFT collection page because I thought the pop_up modal will need it.

**Comment by codeWhizperer** [comment]
@kenkomu Hello, any update on this?

**Comment by kenkomu** [comment]
Yes, I am almost done.

**Comment by codeWhizperer** [comment]
@kenkomu Please check PR conversation, Ieft some comments there. Kindly tag me when you make the changes so I'd receive notification

**Comment by kenkomu** [comment]
Okay.
