### ISSUE TITLE
My NFT Collections page

### ISSUE THREAD

**Issue by i-abdulsalihu** [Starknet-Africa-Edu/TBA-FRONTEND#56]
I'm not sure whether this is intended to happen this way, but rather than showing this 👇 

<img width="1680" alt="Screenshot 2024-03-18 at 14 19 27" src="https://github.com/Starknet-Africa-Edu/TBA-FRONTEND/assets/131313531/89fe1da3-9b5d-4612-b07b-5cabcda03243">

A notification informing the user that they do not yet have an NFT should appear.
If I'm mistaken, do correct me; if not, I can take care of things for you.

**Comment by codeWhizperer** [comment]
@WebSculptor The issue is that the indexer is uanble to return your assets nft metadata. We'd look into this. If a user don't have any nft asset at all, it will render the ```No nft assets```

**Comment by bhavyagosai** [comment]
are there any issues open for contribution?
