### ISSUE TITLE
Fix horizontal scroll on Landing Page

### ISSUE THREAD

**Issue by wheval** [Starknet-Africa-Edu/TBA-FRONTEND#86]
The current implementation of the Landing page shows a horizontal scrollbar on smaller desktop screen sizes because of the overflowing  curved image, which does provide a very good User Experience.

![Screenshot (29)](https://github.com/user-attachments/assets/0d97b89d-1c8a-49d8-aa08-40128afa2237)

**Comment by ooochoche** [comment]
@wheval can I work on this?

**Comment by wheval** [comment]
I'm working on this already. :)
