### ISSUE TITLE
change X icon in Footer to X (Twitter) Icon

### ISSUE THREAD

**Issue by wheval** [Starknet-Africa-Edu/TBA-FRONTEND#88]
Currently, the icon represented here shows an X, which does not correspond to the figma design.
Change the `<XIcon />` to `<TwitterIcon/> in the Footer component`.

![Capture](https://github.com/user-attachments/assets/7c077cb6-f185-4203-bd3a-98b95681020f)

The figma design file.
[FIGMA DESIGN HERE](https://www.figma.com/file/e1Xb0n8gPQ2yKkTco1h7UB?type=design)

**Comment by ShantelPeters** [comment]
Can I please work on this @wheval

**Comment by wheval** [comment]
Sure!

**Comment by ShantelPeters** [comment]
> Sure!

Thank you I’ll get straight to it
